# Generated by Django 2.0.5 on 2018-10-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ssh',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('last_login_date', models.DateTimeField(auto_now=True)),
                ('last_login_time', models.TimeField(auto_now=True)),
                ('introduction', models.TextField(null=True)),
                ('removed', models.BooleanField(default=False)),
            ],
        ),
    ]
