# Generated by Django 2.0.5 on 2018-10-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ssh',
            name='last_login_date',
        ),
        migrations.AlterField(
            model_name='ssh',
            name='last_login_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
